name: Deployment

on:
  workflow_run:
    workflows: ['CI build']
    types:
      - completed

jobs:
  deployment:
    name: Deploy on server
    runs-on: ubuntu-latest
    steps:
      - name: connect to server through SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
